name: appliances_billing
description: "Appliances Shop Billing System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5

  # Networking & API
  dio: ^5.3.2
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0

  # Authentication
  local_auth: ^2.1.7

  # PDF Generation for Invoices
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1

  # Charts & Data Visualization
  fl_chart: ^0.63.0

  # Utils
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700